version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/Yuto-Nakano/shuffle
    steps:
      - checkout
      - run: cd webhook_server && go get -v -d
      - run: cd webhook_server && go test -v

      # TODO: cdでいちいち掘ってるの無駄
      # TODO: lint等もワークフローに組み込みたい
